global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']

  - job_name: 'report-service'
    static_configs:
      - targets: ['host.docker.internal:2112'] # todo: host

  - job_name: 'processor-service'
    static_configs:
      - targets: ['host.docker.internal:2113'] # todo: host
