global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:16686']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8082']

  - job_name: 'processor-service'
    static_configs:
      - targets: ['processor-service:8082']

  - job_name: 'purchase-service'
    static_configs:
      - targets: ['purchase-service:8082']